# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Bryce Parry's Homepage
description: >- # this means to ignore newlines until "baseurl:"
  Bryce Parry's personal homepage.
baseurl: "/" # the subpath of the site
url: "https://mindofbp.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Projects
    - name: CV
      slug: ./assets/Parry_CV.pdf

footer:
  show_powered_by: false
  follow:
    - type: linkedin
      name: LinkedIn
      link: https://www.linkedin.com/in/bryce-parry-9778b01b3/
    - type: github
      name: GitHub
      link: https://github.com/mindofbp

# Build settings
markdown: kramdown
sass:
    style: compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
